/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package island.stuff;

public class SimpleProducer {

    public static void main(String[] args) {
        System.out.println(new SimpleProducer().getGreeting());
    }

    public String getGreeting() {
        return "Hello world.";
    }

}
